<?php /* Smarty version 2.6.0, created on 2011-07-05 18:33:13
         compiled from index.tpl */ ?>
<html lang="en" xmlns:ext="http://extjs.com/docs">
    <head>
        <!-- Generated by phpDocumaentor: <?php echo $this->_tpl_vars['date']; ?>
 -->
        <title><?php echo $this->_tpl_vars['title']; ?>
</title>
        <link rel="stylesheet" type="text/css" href="scripts/extjs/resources/css/ext-all.css" />
        <link rel="stylesheet" type="text/css" href="styles/phpdoc.css"></link>
        <link rel="stylesheet" type="text/css" href="styles/docs.css"></link>
    	<link rel="stylesheet" type="text/css" href="styles/style.css"></link>
    	<link rel="shortcut icon" href="http://www.jackslocum.com/favicon.ico" />
    	<link rel="icon" href="http://www.jackslocum.com/favicon.ico" />
    </head>

    <body scroll="no" id="docs">
        <div id="loading-mask" style=""></div>
        <div id="loading">
            <div class="loading-indicator">
                <img src="images/extanim32.gif" width="32" height="32" style="margin-right:8px;" align="absmiddle"/>
                Loading...
            </div>
        </div>
        
        <!-- Include everything after the loading indicator -->
        <script type="text/javascript" src="scripts/extjs/adapter/ext/ext-base.js"></script>
        <script type="text/javascript" src="scripts/extjs/ext-all.js"></script>
        <script type="text/javascript" src="scripts/TabCloseMenu.js"></script>
        <script type="text/javascript" src="scripts/docs.js"></script>
        <script type="text/javascript" src="scripts/nav_data.js"></script>
        
        <div id="header">
          	<div class="api-title"><?php echo $this->_tpl_vars['title']; ?>
</div>
        </div>
        
        <div id="classes"></div>
        <div id="main"></div>
    </body>
</html>